export const ADDCOMMANDE = "ADDCOMMANDE"

export const GETCOMMANDESWITHCHEFID = "GETCOMMANDEWITHCHEFID"
export const GETCOMMANDESWITHCLIENTID = "GETCOMMANDEWITHCLIENTID"
export const GETCOMMANDESWITHLIVREURID = "GETCOMMANDEWITHLIVREURID"

export const DELETECOMMANDE = "DELETECOMMANDE"

export const GETALLCOMMANDES = "GETALLCOMMANDES"
export const GETONECOMMANDE = "GETONECOMMANDE"