export const ADDFOOD = "ADDFOOD"

export const GETALLFOOD = "GETALLFOOD"
export const FETCHFOODS = "FETCHFOODS"
export const FETCHFOODSOWNERID = "FETCHFOODSOWNERID"

export const GETONEFOOD = "GETONEFOOD"
export const DELETEONEFOOD = "DELETEONEFOOD"
