export const ADDRENDEZVOUS = "ADDRENDEZVOUS"
export const GETALLRENDEZVOUSS = "GETALLRENDEZVOUSS"

export const GETONECHEFRENDEZVOUS = "GETONECHEFRENDEZVOUS"
export const GETONERENDEZVOUS = "GETONERENDEZVOUS"

export const UPDATERENDEZVOUS = "UPDATERENDEZVOUS"
export const DELETERENDEZVOUS = "DELETERENDEZVOUS"